### ISSUE TITLE
gopherjs build problem in 64bit windows 10

### ISSUE THREAD

**Issue by githubfanster** [EngineerKamesh/igb#1]
hi! i can't get past the gopherjs build step after go get ./.. inside  .../igb/igweb/client
 i wonder if it has anything to do with the fact that i'm using go version 1.9.2 but gopherjs version 1.9-1 ??

here are the messages i get in my command console:
f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client>gopherjs build
[31mC:\Go\src\internal\poll\fd_windows.go:386:22: invalid operation: fd.pd (variable of type pollDesc) has no field or method runtimeCtx
[39m[31mC:\Go\src\internal\poll\fd_windows.go:387:22: invalid operation: fd.pd (variable of type pollDesc) has no field or method runtimeCtx
[39m[31mC:\Go\src\internal\poll\fd_windows.go:167:5: invalid operation: o.fd.pd (variable of type pollDesc) has no field or method runtimeCtx
[39m
f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client>

thanks for any info or help!

**Comment by githubfanster** [comment]
did some more digging. this issue has been logged in
https://github.com/gopherjs/gopherjs/issues/688

there's a gopherjs build problem in windows. the workaround is to temporarily set GOOS=darwin when working with gopherjs , for example:

F:\>cd %IGWEB_APP_ROOT%\client

f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client>set GOOS=darwin

f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client>gopherjs build

f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client>dir

 Directory of f:\gowork\src\github.com\EngineerKamesh\igb\igweb\client

01/16/2018  09:00 PM    <DIR>          .
01/16/2018  09:00 PM    <DIR>          ..
01/16/2018  06:37 PM    <DIR>          carsdemo
01/16/2018  06:37 PM    <DIR>          chat
01/16/2018  06:37 PM             3,098 client.go
01/16/2018  09:00 PM         9,241,967 client.js
01/16/2018  09:00 PM           336,172 client.js.map
01/16/2018  06:37 PM    <DIR>          common
01/16/2018  06:37 PM    <DIR>          gopherjsprimer
01/16/2018  06:37 PM    <DIR>          handlers
01/16/2018  06:37 PM    <DIR>          localstoragedemo
01/16/2018  06:37 PM    <DIR>          tests

**Comment by EngineerKamesh** [comment]
Thanks for submitting this issue. This is a known issue in GopherJS v1.9-1 and you have found the workaround. Please follow the Isomorphic Go twitter page, we announced this issue on Dec 31st: https://twitter.com/IsomorphicGo

This issue also affected Kick (since kick does a gopherjs build automatically for you). I had placed a solution for Windows users that takes the workaround into consideration.
