### ISSUE TITLE
Back button not working in IGWEB app

### ISSUE THREAD

**Issue by avdempsey** [EngineerKamesh/igb#4]
Hi Kamesh,

I bought your book a few days ago; I'd been a little jealous of isometric JS, so I am excited to see this!

It looks like the back button isn't completely working in the IGWEB app (running on my local or on your demo site). History is preserved correctly, and the URL changes, but the views aren't loading automatically. Refreshing the page with the URL does work, however.

I've tested on the latest versions of Firefox, Chrome, and Safari on an up-to-date Mac.

**Comment by EngineerKamesh** [comment]
Hi Alex,

Thanks so much for your support, I hope you enjoy the reading the book.

Thanks also for submitting this issue. I have added functionality to the isokit package to allow for back/forward button interactions now. On your local machine, get the latest version of isokit:

`go get -u github.com/isomorphicgo/isokit`

Restart your local igweb server instance, click around to the different sections of igweb. Please try out the forward and back buttons, it should preserve the history now.

I have deployed the lastest version of igweb to http://igweb.kamesh.com. You may need to do a hard refresh (ctrl-command-r) to see the change reflect.

**Comment by EngineerKamesh** [comment]
After you get the latest isokit, please recompile the client-side application, either by doing a `gopherjs build`, or by re-running `kick`.
