### ISSUE TITLE
A minor typing issue(Chapter03)

### ISSUE THREAD

**Issue by surinkim** [EngineerKamesh/igb#5]
Hello, Kamesh

I've found a minor typing issue.
In page86,
`element := js.Get("document").Call("getElementById"), "primaryContent")`

This code should be
`element := js.Get("document").Call("getElementById", "primaryContent")`

I think your book is amazing!
Thank you for your valuable time and sharing valuable idea :)

**Comment by EngineerKamesh** [comment]
Hello Hyunuk Kim,

Thank you so much for pointing out this issue. I will add it to the errata list.

Thank you for your kind words about the Isomorphic Go book and for your support!

Best,
Kamesh
